const PERCENTAGE_FOR_JACKPOT = (7 / 100);
const PERCENTAGE_FOR_DIAMOND = (25 / 100);
const MAXIMUM_OF_FLAME = 20;

module.exports = {
  PERCENTAGE_FOR_JACKPOT,
  PERCENTAGE_FOR_DIAMOND,
  MAXIMUM_OF_FLAME
};
